version: "3.7"

services:
  listchat:
    # image: "listchat"
    image: "repo.korkla.in/mon-listchat"
    ports:
      - "3100:4000"
    # environment:
    #   - ENV=uat
    env_file:
      - .env
    restart: always
